function snapip() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/snapip", "_self") }
function snapx() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/snap-x", "_self") }
function snapchatx2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/snapchat-x-2", "_self") }
function snapchatplus() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/snapchat-plus", "_self") }
function snapchatplus2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/snapchat-plus-two", "_self") }
function vshack() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/vshack", "_self") }
function vspro() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/vspro", "_self") }
function dltiktok() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/dl-tiktok", "_self") }
function tiktokdark() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/tiktok-dark", "_self") }
function tiktokauto() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/tiktok-auto", "_self") }
function tiktokautodl() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/tiktok-auto-dl", "_self") }
function dlinsta() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/dl-insta", "_self") }
function instarock() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/insta-rock", "_self") }
function facebook() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/facebook", "_self") }
function messager() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/messager", "_self") }
function dlyoutube() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/dl-youtube", "_self") }
function discord() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/discord", "_self") }
function pubgv1() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/pubg-v1", "_self") }
function pubgv2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/pubg-v2", "_self") }
function pubgv3() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/pubg-v2", "_self") }
function crossdj() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/cross-dj", "_self") }
function djaypro() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/djay-pro", "_self") }
function rimini() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/rimini", "_self") }
function facetune() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/facetune", "_self") }
function inshot() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/inshot", "_self") }
function lightroom() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/lightroom", "_self") }
function picsart() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/picsart", "_self") }
function alightmotion() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/alight-motion", "_self") }
function lumafusion() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/luma-fusion", "_self") }
function netflix() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/netflix", "_self") }
function ppsspp() { window.open("itms-services://?action=download-manifest&url=https://saadnaman.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/ppsspp", "_self") }
function photoshop() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/photoshop", "_self") }
function quranmajeed() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/quran-majeed", "_self") }
function tempoapp() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/tempo-app", "_self") }
function videofxlive() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/video-fx-live", "_self") }
function vivacut() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/viva-cut", "_self") }
function clashofclans() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/clash-of-clans", "_self") }
function clashroyal() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/clash-royal", "_self") }
function minecraft() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/minecraft", "_self") }
function traficracer() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/trafic-racer", "_self") }
function human() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/human", "_self") }
function gittingover() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/gitting-over", "_self") }
function extremecar() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/extreme-car", "_self") }
function bike() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/bike", "_self") }
function raftonline() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/raft-online", "_self") }
function pccreator2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/pc-creator2", "_self") }
function fifamobile() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/fifa-monile", "_self") }
function drdriving() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/dr-driving", "_self") }
function housedesigner() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/house-designer", "_self") }
function templerun2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/temple-run-2", "_self") }
function subwaysurfers() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/subway-surfers", "_self") }
function truckofeurope3() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/truck-of-europe-3", "_self") }
function carxstreet() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/car-x-street", "_self") }
function carx2() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/car-x-2", "_self") }
function org2023() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/org-2023", "_self") }
function carparking() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/car-parking", "_self") }
function gtakrd() { window.open("itms-services://?action=download-manifest&url=https://adovip.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/gta-krd", "_self") }
function esign() { window.open("itms-services://?action=download-manifest&url=https://saadnaman.store/ADO345AdO/ZzhanyaR2007/PliST123PliSSsT/esign", "_self") }
